### ISSUE TITLE
:bug: Bug: poseidon.parameters.case_simple()

### ISSUE THREAD

**Issue by alv-around** [ingonyama-zk/poseidon-hash#6]
Hello!

playing with the library, I think I found a bug 🕵️ 

so I was trying to run this snippet taken from the [pypi site](https://pypi.org/project/poseidon-hash/0.1.2/):
```python
import poseidon


poseidon_simple, t = poseidon.parameters.case_simple()

input_vec = [x for x in range(0, t)]
print("Input: ", input_vec)
poseidon_digest = poseidon_simple.run_hash(input_vec)
print("Output: ", hex(int(poseidon_digest)))
```

And I get the following error:
```sh
Traceback (most recent call last):
  File "/Users/alv/code/zokrates+/tutorials/hashes/poseidon/witnessx.py", line 4, in <module>
    poseidon_simple, t = poseidon.parameters.case_simple()
  File "/Users/alv/.pyenv/versions/pycrypto/lib/python3.9/site-packages/poseidon/parameters.py", line 12, in case_simple
    poseidon = Poseidon(prime_64, security_level, alpha, input_rate, t, full_round=full_round,
  File "/Users/alv/.pyenv/versions/pycrypto/lib/python3.9/site-packages/poseidon/hash.py", line 45, in __init__
    if np.gcd(alpha, p - 1) == 1:
numpy.core._exceptions.UFuncTypeError: ufunc 'gcd' did not contain a loop with signature matching types (<class 'numpy.dtype[int64]'>, <class 'numpy.dtype[ulonglong]'>) -> None
```

versions:
Python: 3.9.7
numpy==1.22.4
poseidon-hash==0.1.2

Just FYI :)

cheers

**Comment by omershlo** [comment]
thanks @alvaro-alonso ! 
seems like a version issue. we will take a look 
cc: @seemenkina

**Comment by seemenkina** [comment]
@alvaro-alonso thanks for noticing, I've fixed bug
